# Generated by Django 5.2.7 on 2025-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_project_leader_alter_project_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["deadline"]},
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("name", "project"), name="unique_task_name_per_project"
            ),
        ),
    ]
