# Generated by Django 5.2.7 on 2025-11-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_options_task_unique_task_name_per_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "deadline"], name="tasks_task_project_48bed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_completed"], name="tasks_task_is_comp_30fbc3_idx"
            ),
        ),
    ]
