# Generated by Django 5.2.7 on 2025-10-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_project_tasks_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
