# Generated by Django 5.2.7 on 2025-10-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasktype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
