# Generated by Django 5.2.7 on 2025-10-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_worker_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
