# Generated by Django 5.2.7 on 2025-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_worker_first_name_alter_worker_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='biography',
            field=models.TextField(blank=True, default=''),
        ),
    ]
