# Generated by Django 5.2.7 on 2025-11-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_worker_first_name_alter_worker_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="description",
        ),
    ]
