# Generated by Django 5.2.7 on 2025-11-10 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_remove_team_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="tasks.project"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
